name: simulation_tool
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: timalenus <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  firebase: '^4.0.0'

dev_dependencies:
  test: ^0.12.0
  partago_model:
    path: ../../../../../_PARTAGO/partago_model
  firebase_dart: any
